### ISSUE TITLE
longitude limit overwrite caused mapping error

### ISSUE THREAD

**Issue by chaincy-cal** [IPCC-WG1/Chapter-6_Fig10#1]
### Issue Fixed  
Longitude mapping error for IPCC AR6 WG1 Figure 6.10b is fixed.  The correction leads to a change in regional aggregation of shortwave and longwave components of aerosol ERF.   The fix can currently be found on branch 'correctFig10b' (https://github.com/IPCC-WG1/Chapter-6_Fig10/tree/correctFig10b).    All sourced data and processed data are  correct.  IPCC AR6 WG1 text and  Figure 6.11 referring to Figure 6.10b are correct and require no change.  The fix has been confirmed with IPCC AR6 WG1 Chapter 6 Coordinating Lead Authors.

**Comment by chaincy-cal** [comment]
### Issue Fixed  
Longitude mapping error for IPCC AR6 WG1 Figure 6.10b is fixed.  The correction leads to a change in attribution.   The fix can currently be found on fork [](https://github.com/chaincy-cal/Chapter-6_Fig10).    All sourced data and processed data are  correct.  IPCC AR6 WG1 text and  Figure 6.11 referring to Figure 6.10b are correct and require no change.  The fix has been confirmed with IPCC AR6 WG1 Chapter 6 Coordinating Lead Authors.

**Comment by chaincy-ipcc** [comment]
# Merged to Main

The fix can currently be found on the main branch (https://github.com/IPCC-WG1/Chapter-6_Fig10/tree/main).

**Comment by chaincy-ipcc** [comment]
Closing issue after checking that links in README.md in main branch link to code as expected.
